#ifndef RESPONSE_H_
#define RESPONSE_H_

#define MAX_LENGHT_FILE 100000
typedef enum{
    GENERIC_ERROR,
    O_CREATE_NOT_SPECIFIED_AND_FILE_NEXIST,
    FILE_ALREADY_OPENED,
    FILE_ALREADY_EXIST,
    CANNOT_ACCESS_FILE_LOCKED,
    FILE_NOT_EXIST,

    OPEN_FILE_SUCCESS,
    READ_FILE_SUCCESS,
    READ_N_FILE_SUCCESS,
    WRITE_FILE_SUCCESS,
    O_CREATE_SUCCESS,
    O_LOCK_SUCCESS,
    O_CREATE_LOCK_SUCCESS,
    APPEND_FILE_SUCCESS,
    REMOVE_FILE_SUCCESS,
    CLOSE_FILE_SUCCESS,
    LOCK_FILE_SUCCESS,
    UNLOCK_FILE_SUCCESS,

    NO_SPACE_IN_SERVER,
    WRITE_FILE_FAILURE,
    READ_N_FILE_FAILURE,
    FILE_NOT_OPEN,
    FILE_NOT_LOCKED

}response_type;

typedef struct s{
    response_type type;
    int flags;
    int c; //contatore generico
    void * content;
    size_t size;
}response;

#endif