#ifndef RESPONSE_H_
#define RESPONSE_H_

typedef enum{
    O_CREATE_NOT_SPECIFIED_AND_FILE_NEXIST,
    CANNOT_CREATE_FILE,
    FILE_ALREADY_OPENED,
    FILE_ALREADY_EXIST,
    CANNOT_ACCESS_FILE_LOCKED,

    OPEN_FILE_SUCCESS,
    O_CREATE_SUCCESS,
    LOCK_FILE_SUCCESS,

    FILE_NOT_OPENED

}response;


#endif